_wandb:
    value:
        cli_version: 0.22.3
        e:
            wkeqzrw43k9k1kpt4qcdli0mp6ziwlj6:
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "500496855040"
                        used: "207842127872"
                email: tzuhsuan5684@gmail.com
                executable: C:\Users\user\anaconda3\python.exe
                git:
                    commit: aa4f4aa23e4a846a811865eebbd2c9182ffbc5be
                    remote: https://github.com/tzuhsuan5684/TTMATCH
                host: LAPTOP-4F2BAF37
                memory:
                    total: "16948453376"
                os: Windows-10-10.0.26100-SP0
                program: D:\class\資料科學\main.py
                python: CPython 3.11.5
                root: D:\class\資料科學
                startedAt: "2025-11-01T13:20:54.099053Z"
                writerId: wkeqzrw43k9k1kpt4qcdli0mp6ziwlj6
        m: []
        python_version: 3.11.5
        t:
            "1":
                - 2
                - 3
                - 5
                - 49
                - 53
                - 105
            "2":
                - 2
                - 3
                - 5
                - 49
                - 53
                - 105
            "3":
                - 2
                - 16
                - 39
                - 62
            "4": 3.11.5
            "5": 0.22.3
            "8":
                - 3
            "12": 0.22.3
            "13": windows-amd64
        visualize:
            conf_mat_action:
                panel_config:
                    fieldSettings:
                        Actual: Actual
                        Predicted: Predicted
                        nPredictions: nPredictions
                    panelDefId: wandb/confusion_matrix/v1
                    stringSettings:
                        title: CM ActionID (Val)
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: conf_mat_action_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            conf_mat_point:
                panel_config:
                    fieldSettings:
                        Actual: Actual
                        Predicted: Predicted
                        nPredictions: nPredictions
                    panelDefId: wandb/confusion_matrix/v1
                    stringSettings:
                        title: CM PointID (Val)
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: conf_mat_point_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            conf_mat_server:
                panel_config:
                    fieldSettings:
                        Actual: Actual
                        Predicted: Predicted
                        nPredictions: nPredictions
                    panelDefId: wandb/confusion_matrix/v1
                    stringSettings:
                        title: CM ServerGetPoint (Val)
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: conf_mat_server_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
batch_size:
    value: 64
dropout:
    value: 0.3
epochs:
    value: 8
learning_rate:
    value: 0.001
loss_action:
    value: focal_loss
loss_point:
    value: focal_loss
lstm_units:
    value: 128
max_seq_len:
    value: 10
